#Exercicio aula 26/04/2018

use ADS181_BIBLIOTECA;
select USUARIOS.ID, NOME, SOBRENOME, TIPO_USUARIO, NOME_ESTADO, LIVROS.ID, TITULO,
CATEGORIA,PRECO
from USUARIOS
inner join LIVROS on USUARIOS.ID = LIVROS.USUARIO_ID
inner join ESTADOS on USUARIOS.SIGLA_ESTADO = ESTADOS.SIGLA_ESTADO
where TIPO_USUARIO = 'ALUNO' and ESTADOS.SIGLA_ESTADO = 'SC';