#Inserir 5 registros em cada tabela (TABELA USUARIOS)
use bdii182_biblioteca;
#1
INSERT USUARIOS(ID, NOME, SOBRENOME, ENDERECO, CIDADE, SIGLA_ESTADO, TELEFONE, TIPO_USUARIO)
VALUES (1, 'NOME1', 'SOBRENOME1', 'ENDERECO1', 'CIDADE1', 'RS', '1111-1111', 'PROFESSOR');
#2
INSERT USUARIOS(ID, NOME, SOBRENOME, ENDERECO, CIDADE, SIGLA_ESTADO, TELEFONE, TIPO_USUARIO)
VALUES (2, 'NOME2', 'SOBRENOME2', 'ENDERECO2', 'CIDADE2', 'SC', '2222-2222', 'ALUNO');
#3
INSERT USUARIOS(ID, NOME, SOBRENOME, ENDERECO, CIDADE, SIGLA_ESTADO, TELEFONE, TIPO_USUARIO)
VALUES (3, 'NOME3', 'SOBRENOME3', 'ENDERECO3', 'CIDADE3', 'SP', '3333-3333', 'FUNCIONARIO');
#4
INSERT USUARIOS(ID, NOME, SOBRENOME, ENDERECO, CIDADE, SIGLA_ESTADO, TELEFONE, TIPO_USUARIO)
VALUES (4, 'NOME4', 'SOBRENOME4', 'ENDERECO4', 'CIDADE4', 'SC', '4444-4444', 'PROFESSOR');
#5
INSERT USUARIOS(ID, NOME, SOBRENOME, ENDERECO, CIDADE, SIGLA_ESTADO, TELEFONE, TIPO_USUARIO)
VALUES (5, 'NOME5', 'SOBRENOME5', 'ENDERECO5', 'CIDADE5', 'RJ', '5555-5555', 'ALUNO');