#Inserir 5 registros em cada tabela (TABELA LIVROS)
use BDII182_BIBLIOTECA;
#1
INSERT LIVROS(ID, USUARIO_ID, TITULO, ANO_PUBLICACAO, NUMERO_EDICAO, PAGINAS, CATEGORIA, PRECO)
VALUES (1, 5, 'TITULO1', 2001, 1, 111, 'ROMANCE', 100);
#2
INSERT LIVROS(ID, USUARIO_ID, TITULO, ANO_PUBLICACAO, NUMERO_EDICAO, PAGINAS, CATEGORIA, PRECO)
VALUES (2, 4, 'TITULO2', 2002, 2, 222, 'DIDATICO', 200);
#3
INSERT LIVROS(ID, USUARIO_ID, TITULO, ANO_PUBLICACAO, NUMERO_EDICAO, PAGINAS, CATEGORIA, PRECO)
VALUES (3, 3, 'TITULO3', 2003, 3, 333, 'FICCAO', 300);
#4
INSERT LIVROS(ID, USUARIO_ID, TITULO, ANO_PUBLICACAO, NUMERO_EDICAO, PAGINAS, CATEGORIA, PRECO)
VALUES (4, 4, 'TITULO4', 2004, 4, 444, 'ROMANCE', 400);
#5
INSERT LIVROS(ID, USUARIO_ID, TITULO, ANO_PUBLICACAO, NUMERO_EDICAO, PAGINAS, CATEGORIA, PRECO)
VALUES (5, 2, 'TITULO5', 2005, 5, 555, 'CIENTIFICO', 500);