#Inserir 5 registros em cada tabela (TABELA ESTADOS)
use BDII182_BIBLIOTECA;
#1
INSERT ESTADOS(SIGLA_ESTADO, NOME_ESTADO)
VALUES ('RS', 'RIO GRANDE DO SUL');
#2
INSERT ESTADOS(SIGLA_ESTADO, NOME_ESTADO)
VALUES ('SC', 'SANTA CATARINA');
#3
INSERT ESTADOS(SIGLA_ESTADO, NOME_ESTADO)
VALUES ('PR', 'PARANA');
#4
INSERT ESTADOS(SIGLA_ESTADO, NOME_ESTADO)
VALUES ('RJ', 'RIO DE JANEIRO');
#5
INSERT ESTADOS(SIGLA_ESTADO, NOME_ESTADO)
VALUES ('SP', 'SAO PAULO');