#altera o campo sigla_estados na tabela ESTADOS

use BDII182_BIBLIOTECA;

ALTER TABLE USUARIOS 
ADD CONSTRAINT FK_USUARIOS_ESTADOS
FOREIGN KEY (SIGLA_ESTADO)
REFERENCES ESTADOS(SIGLA_ESTADO)
ON DELETE RESTRICT
ON UPDATE RESTRICT;